
- name: cvuqdisk
  yum:
    name: cvuqdisk
    disable_gpg_check: yes

- name: Extend the u01 mountpoint
  lvol:
    vg: vg01
    lv: u01
    size: 80G
    shrink: no
    resizefs: yes

- name: Mount /dev/shm ASM uses AMM
  mount:
    fstype: tmpfs
    path: /dev/shm
    src: tmpfs
    opts: "size=2G"
    state: mounted

- name: Set authorized key took from file
  authorized_key:
    user: "{{ oracle_os_user }}"
    state: present
    #key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}" # Local key file from ansible host
    key: "{{ lookup('file', './files/keys/id_rsa.pub') }}"

- name: ensure private key and public one are present
  copy: 
    src: keys/
    dest: "/home/{{ oracle_os_user }}/.ssh/"
    mode: 0400
    owner: "{{ oracle_os_user }}"
    group: "{{ oracle_os_group }}"
  with_items:
    - id_rsa

- name: Accept ssh keys from all other cluster nodes
  shell: "ssh -oStrictHostKeyChecking=no {{ item }} hostname"
  become: yes
  become_user: "{{ oracle_os_user }}"
  with_items:
    - "{{ ansible_play_batch }}"
